"""
HTML Report Generator — Creates professional reports with embedded charts.

Uses matplotlib for chart generation and embeds them as base64 images
in a self-contained HTML file.
"""

import base64
import io
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from typing import Dict, Any
from datetime import datetime


def _fig_to_base64(fig) -> str:
    """Convert matplotlib figure to base64 string."""
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=150, bbox_inches="tight",
                facecolor="white", edgecolor="none")
    buf.seek(0)
    b64 = base64.b64encode(buf.read()).decode("utf-8")
    plt.close(fig)
    return b64


def _html_wrapper(title: str, content: str) -> str:
    """Wrap content in styled HTML template."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{title} — FoodMC Report</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
               background: #f0f2f5; color: #1a1a2e; line-height: 1.6; }}
        .header {{ background: linear-gradient(135deg, #0f3460 0%, #16213e 100%);
                   color: white; padding: 40px; text-align: center; }}
        .header h1 {{ font-size: 28px; margin-bottom: 8px; letter-spacing: -0.5px; }}
        .header .subtitle {{ color: #94a3b8; font-size: 14px; }}
        .header .badge {{ display: inline-block; background: rgba(255,255,255,0.15);
                         padding: 4px 14px; border-radius: 20px; font-size: 12px;
                         margin-top: 12px; }}
        .container {{ max-width: 960px; margin: 0 auto; padding: 30px 20px; }}
        .card {{ background: white; border-radius: 12px; padding: 28px;
                 margin-bottom: 24px; box-shadow: 0 1px 4px rgba(0,0,0,0.06); }}
        .card h2 {{ font-size: 18px; color: #0f3460; margin-bottom: 16px;
                    padding-bottom: 10px; border-bottom: 2px solid #e8eaf0; }}
        .metric-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
                        gap: 16px; margin-bottom: 20px; }}
        .metric {{ background: #f8f9fc; padding: 16px; border-radius: 8px;
                   border-left: 4px solid #3b82f6; }}
        .metric .label {{ font-size: 11px; text-transform: uppercase; color: #64748b;
                          letter-spacing: 0.5px; margin-bottom: 4px; }}
        .metric .value {{ font-size: 22px; font-weight: 700; color: #1e293b; }}
        .metric .detail {{ font-size: 12px; color: #94a3b8; margin-top: 2px; }}
        .metric.green {{ border-left-color: #22c55e; }}
        .metric.red {{ border-left-color: #ef4444; }}
        .metric.amber {{ border-left-color: #f59e0b; }}
        table {{ width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 14px; }}
        th {{ background: #f1f5f9; color: #475569; padding: 10px 12px; text-align: left;
              font-weight: 600; font-size: 12px; text-transform: uppercase; letter-spacing: 0.3px; }}
        td {{ padding: 10px 12px; border-bottom: 1px solid #f1f5f9; }}
        tr:hover {{ background: #f8fafc; }}
        img.chart {{ width: 100%; border-radius: 8px; margin: 12px 0; }}
        .footer {{ text-align: center; padding: 30px; color: #94a3b8; font-size: 12px; }}
        .risk-low {{ color: #22c55e; font-weight: 600; }}
        .risk-medium {{ color: #f59e0b; font-weight: 600; }}
        .risk-high {{ color: #f97316; font-weight: 600; }}
        .risk-critical {{ color: #ef4444; font-weight: 600; }}
        .two-col {{ display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }}
        @media (max-width: 700px) {{ .two-col {{ grid-template-columns: 1fr; }} }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🧪 {title}</h1>
        <div class="subtitle">Generated by FoodMC — Monte Carlo Simulation Toolkit for Food R&D</div>
        <div class="badge">📅 {datetime.now().strftime("%B %d, %Y at %I:%M %p")}</div>
    </div>
    <div class="container">
        {content}
    </div>
    <div class="footer">
        Generated by <strong>FoodMC v1.0</strong> — Monte Carlo Simulation Toolkit for Food R&D<br>
        🔗 github.com/yourusername/foodmc
    </div>
</body>
</html>"""


# ═══════════════════════════════════════════════════════════════
# FORMULATION REPORT
# ═══════════════════════════════════════════════════════════════

def generate_formulation_report(result, filepath: str) -> str:
    """Generate formulation simulation HTML report."""
    stats = result.summary()

    # ── Cost Distribution Chart ──────────────────────────────
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.hist(result.total_costs, bins=80, color="#3b82f6", alpha=0.8, edgecolor="white")
    ax.axvline(stats["mean"], color="#ef4444", linewidth=2, linestyle="--", label=f"Mean: ₹{stats['mean']:.2f}")
    ax.axvline(stats["p5"], color="#f59e0b", linewidth=1.5, linestyle=":", label=f"P5: ₹{stats['p5']:.2f}")
    ax.axvline(stats["p95"], color="#f59e0b", linewidth=1.5, linestyle=":", label=f"P95: ₹{stats['p95']:.2f}")
    ax.set_xlabel("Total Batch Cost (₹)", fontsize=12)
    ax.set_ylabel("Frequency", fontsize=12)
    ax.set_title("Total Formulation Cost Distribution", fontsize=14, fontweight="bold")
    ax.legend(fontsize=10)
    ax.grid(axis="y", alpha=0.3)
    cost_chart = _fig_to_base64(fig)

    # ── Ingredient Cost Contribution Chart ───────────────────
    fig, ax = plt.subplots(figsize=(10, 5))
    ing_names = [i.name for i in result.ingredients]
    ing_means = [np.mean(result.ingredient_costs[n]) for n in ing_names]
    ing_stds = [np.std(result.ingredient_costs[n]) for n in ing_names]
    colors = plt.cm.Set2(np.linspace(0, 1, len(ing_names)))
    bars = ax.barh(ing_names, ing_means, xerr=ing_stds, color=colors,
                   edgecolor="white", capsize=4)
    ax.set_xlabel("Cost Contribution (₹)", fontsize=12)
    ax.set_title("Ingredient Cost Contributions (Mean ± Std)", fontsize=14, fontweight="bold")
    ax.grid(axis="x", alpha=0.3)
    ingredient_chart = _fig_to_base64(fig)

    # ── Pie Chart ────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(7, 7))
    ax.pie(ing_means, labels=ing_names, colors=colors, autopct="%1.1f%%",
           startangle=90, pctdistance=0.85)
    ax.set_title("Cost Share by Ingredient", fontsize=14, fontweight="bold")
    pie_chart = _fig_to_base64(fig)

    # ── Build HTML ───────────────────────────────────────────
    cost_table = result.cost_breakdown().to_html(index=False, classes="")
    nutrition_html = ""
    if not result.nutrition_summary().empty:
        nutrition_html = f"""
        <div class="card">
            <h2>🥗 Nutritional Profile (per 100g of product)</h2>
            {result.nutrition_summary().to_html(index=False, classes="")}
        </div>"""

    content = f"""
    <div class="card">
        <h2>📋 Simulation Summary</h2>
        <div class="metric-grid">
            <div class="metric">
                <div class="label">Mean Batch Cost</div>
                <div class="value">₹{stats['mean']:.2f}</div>
                <div class="detail">per {result.ingredients[0].unit.split('/')[0] if result.ingredients else ''} batch</div>
            </div>
            <div class="metric green">
                <div class="label">Best Case (P5)</div>
                <div class="value">₹{stats['p5']:.2f}</div>
            </div>
            <div class="metric red">
                <div class="label">Worst Case (P95)</div>
                <div class="value">₹{stats['p95']:.2f}</div>
            </div>
            <div class="metric amber">
                <div class="label">Cost Variability (CV)</div>
                <div class="value">{stats['cv']:.1f}%</div>
            </div>
            <div class="metric">
                <div class="label">Simulations</div>
                <div class="value">{result.n_simulations:,}</div>
            </div>
            <div class="metric">
                <div class="label">Ingredients</div>
                <div class="value">{len(result.ingredients)}</div>
            </div>
        </div>
    </div>

    <div class="card">
        <h2>📊 Cost Distribution</h2>
        <img class="chart" src="data:image/png;base64,{cost_chart}" alt="Cost Distribution">
    </div>

    <div class="card">
        <h2>🧩 Ingredient Cost Breakdown</h2>
        {cost_table}
        <div class="two-col">
            <img class="chart" src="data:image/png;base64,{ingredient_chart}" alt="Ingredient Costs">
            <img class="chart" src="data:image/png;base64,{pie_chart}" alt="Cost Pie">
        </div>
    </div>

    {nutrition_html}
    """

    html = _html_wrapper("Formulation Cost Simulation", content)
    with open(filepath, "w") as f:
        f.write(html)
    print(f"📄 Report saved: {filepath}")
    return filepath


# ═══════════════════════════════════════════════════════════════
# SHELF LIFE REPORT
# ═══════════════════════════════════════════════════════════════

def generate_shelflife_report(result, filepath: str) -> str:
    """Generate shelf life simulation HTML report."""
    stats = result.summary()
    params = result.parameters
    rec_95 = result.recommended_shelf_life(0.95)
    rec_99 = result.recommended_shelf_life(0.99)

    # ── Shelf Life Distribution ──────────────────────────────
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.hist(result.shelf_lives, bins=80, color="#22c55e", alpha=0.8, edgecolor="white")
    ax.axvline(stats["mean"], color="#ef4444", linewidth=2, linestyle="--",
               label=f"Mean: {stats['mean']:.0f} days")
    ax.axvline(rec_95, color="#f59e0b", linewidth=2, linestyle="--",
               label=f"95% Safe: {rec_95:.0f} days")
    ax.set_xlabel("Shelf Life (days)", fontsize=12)
    ax.set_ylabel("Frequency", fontsize=12)
    ax.set_title("Shelf Life Distribution", fontsize=14, fontweight="bold")
    ax.legend(fontsize=10)
    ax.grid(axis="y", alpha=0.3)
    sl_chart = _fig_to_base64(fig)

    # ── Degradation Curve ────────────────────────────────────
    curves = result.degradation_curves
    max_time = min(int(stats["p95"] * 1.5), len(curves["time"]))
    fig, ax = plt.subplots(figsize=(10, 5))
    t = curves["time"][:max_time]
    ax.fill_between(t, curves["pessimistic"][:max_time], curves["optimistic"][:max_time],
                    alpha=0.2, color="#3b82f6", label="90% Confidence Band")
    ax.plot(t, curves["mean"][:max_time], color="#3b82f6", linewidth=2, label="Mean Degradation")
    ax.axhline(params["threshold"], color="#ef4444", linewidth=2, linestyle="--",
               label=f"Threshold: {params['threshold']}")
    ax.set_xlabel("Time (days)", fontsize=12)
    ax.set_ylabel(params["quality_attribute"], fontsize=12)
    ax.set_title("Quality Degradation Over Time", fontsize=14, fontweight="bold")
    ax.legend(fontsize=10)
    ax.grid(alpha=0.3)
    deg_chart = _fig_to_base64(fig)

    # ── Survival Curve ───────────────────────────────────────
    fig, ax = plt.subplots(figsize=(10, 5))
    sorted_sl = np.sort(result.shelf_lives)
    survival = 1 - np.arange(1, len(sorted_sl) + 1) / len(sorted_sl)
    ax.plot(sorted_sl, survival * 100, color="#8b5cf6", linewidth=2)
    ax.axhline(5, color="#ef4444", linewidth=1, linestyle=":", alpha=0.7, label="5% failure")
    ax.axhline(1, color="#ef4444", linewidth=1, linestyle="--", alpha=0.7, label="1% failure")
    ax.set_xlabel("Days", fontsize=12)
    ax.set_ylabel("Survival Probability (%)", fontsize=12)
    ax.set_title("Product Survival Curve", fontsize=14, fontweight="bold")
    ax.legend(fontsize=10)
    ax.grid(alpha=0.3)
    surv_chart = _fig_to_base64(fig)

    content = f"""
    <div class="card">
        <h2>📋 Shelf Life Summary</h2>
        <div class="metric-grid">
            <div class="metric green">
                <div class="label">Recommended Shelf Life (95%)</div>
                <div class="value">{rec_95:.0f} days</div>
                <div class="detail">95% of batches safe by this date</div>
            </div>
            <div class="metric">
                <div class="label">Mean Shelf Life</div>
                <div class="value">{stats['mean']:.0f} days</div>
            </div>
            <div class="metric amber">
                <div class="label">Conservative (99%)</div>
                <div class="value">{rec_99:.0f} days</div>
            </div>
            <div class="metric">
                <div class="label">Std Deviation</div>
                <div class="value">{stats['std']:.1f} days</div>
            </div>
            <div class="metric">
                <div class="label">Storage Temp</div>
                <div class="value">{params['temp_mean']:.0f}°C ± {params['temp_std']:.0f}°C</div>
            </div>
            <div class="metric">
                <div class="label">Simulations</div>
                <div class="value">{result.n_simulations:,}</div>
            </div>
        </div>
    </div>

    <div class="card">
        <h2>📊 Shelf Life Distribution</h2>
        <img class="chart" src="data:image/png;base64,{sl_chart}" alt="Shelf Life Distribution">
    </div>

    <div class="card">
        <h2>📉 Quality Degradation Curve</h2>
        <img class="chart" src="data:image/png;base64,{deg_chart}" alt="Degradation Curve">
    </div>

    <div class="card">
        <h2>📈 Product Survival Curve</h2>
        <img class="chart" src="data:image/png;base64,{surv_chart}" alt="Survival Curve">
    </div>

    <div class="card">
        <h2>⚙️ Simulation Parameters</h2>
        <table>
            <tr><th>Parameter</th><th>Value</th></tr>
            <tr><td>Activation Energy (Ea)</td><td>{params['ea_mean']} ± {params['ea_std']} kJ/mol</td></tr>
            <tr><td>Storage Temperature</td><td>{params['temp_mean']} ± {params['temp_std']} °C</td></tr>
            <tr><td>Initial Quality</td><td>{params['initial_quality']} ± {params['quality_std']}</td></tr>
            <tr><td>Quality Threshold</td><td>{params['threshold']}</td></tr>
            <tr><td>Reaction Order</td><td>{params['reaction_order']}</td></tr>
            <tr><td>Reference Rate</td><td>{params['ref_rate']} ± {params['ref_rate_std']} /day</td></tr>
        </table>
    </div>
    """

    html = _html_wrapper("Shelf Life Prediction", content)
    with open(filepath, "w") as f:
        f.write(html)
    print(f"📄 Report saved: {filepath}")
    return filepath


# ═══════════════════════════════════════════════════════════════
# QUALITY REPORT
# ═══════════════════════════════════════════════════════════════

def generate_quality_report(result, filepath: str) -> str:
    """Generate quality control simulation HTML report."""

    charts_html = ""
    for param in result.parameters:
        name = param["name"]
        sims = result.simulations[name]
        cpk = result.cpk_values[name]

        # ── Process Histogram with Spec Limits ───────────────
        fig, axes = plt.subplots(1, 2, figsize=(14, 5))

        ax = axes[0]
        ax.hist(sims, bins=80, color="#3b82f6", alpha=0.8, edgecolor="white", density=True)
        ax.axvline(param["lsl"], color="#ef4444", linewidth=2, linestyle="--", label=f"LSL: {param['lsl']}")
        ax.axvline(param["usl"], color="#ef4444", linewidth=2, linestyle="--", label=f"USL: {param['usl']}")
        ax.axvline(param["target"], color="#22c55e", linewidth=2, linestyle="-", label=f"Target: {param['target']}")
        ax.set_title(f"{name} — Process Distribution", fontsize=13, fontweight="bold")
        ax.set_xlabel(f"{name} ({param['unit']})" if param["unit"] else name)
        ax.legend(fontsize=9)
        ax.grid(axis="y", alpha=0.3)

        ax = axes[1]
        ax.hist(cpk, bins=60, color="#8b5cf6", alpha=0.8, edgecolor="white")
        ax.axvline(1.0, color="#ef4444", linewidth=2, linestyle="--", label="Cpk = 1.0 (minimum)")
        ax.axvline(1.33, color="#f59e0b", linewidth=2, linestyle="--", label="Cpk = 1.33 (good)")
        ax.set_title(f"{name} — Cpk Distribution", fontsize=13, fontweight="bold")
        ax.set_xlabel("Cpk")
        ax.legend(fontsize=9)
        ax.grid(axis="y", alpha=0.3)

        plt.tight_layout()
        chart_b64 = _fig_to_base64(fig)

        prob_in_spec = result.probability_in_spec(name) * 100
        mean_cpk = np.mean(cpk)
        cpk_color = "green" if mean_cpk >= 1.33 else ("amber" if mean_cpk >= 1.0 else "red")

        charts_html += f"""
        <div class="card">
            <h2>📏 {name}</h2>
            <div class="metric-grid">
                <div class="metric {cpk_color}">
                    <div class="label">Mean Cpk</div>
                    <div class="value">{mean_cpk:.3f}</div>
                </div>
                <div class="metric {'green' if prob_in_spec >= 99 else 'red'}">
                    <div class="label">In-Spec Rate</div>
                    <div class="value">{prob_in_spec:.2f}%</div>
                </div>
                <div class="metric">
                    <div class="label">Process Mean</div>
                    <div class="value">{np.mean(sims):.3f} {param['unit']}</div>
                </div>
                <div class="metric">
                    <div class="label">Process Std</div>
                    <div class="value">{np.std(sims):.4f}</div>
                </div>
            </div>
            <img class="chart" src="data:image/png;base64,{chart_b64}" alt="{name} Charts">
        </div>
        """

    summary_table = result.summary().to_html(index=False, classes="")

    content = f"""
    <div class="card">
        <h2>📋 Quality Control Summary</h2>
        {summary_table}
    </div>
    {charts_html}
    """

    html = _html_wrapper("Quality Control Simulation", content)
    with open(filepath, "w") as f:
        f.write(html)
    print(f"📄 Report saved: {filepath}")
    return filepath


# ═══════════════════════════════════════════════════════════════
# NUTRITION REPORT
# ═══════════════════════════════════════════════════════════════

def generate_nutrition_report(result, filepath: str) -> str:
    """Generate nutrition compliance simulation HTML report."""
    overall = result.overall_compliance()
    overall_color = "green" if overall >= 0.95 else ("amber" if overall >= 0.90 else "red")

    charts_html = ""
    for nut in result.nutrients:
        sims = result.simulations[nut.name]
        comp = result.compliance[nut.name]

        fig, ax = plt.subplots(figsize=(10, 5))
        ax.hist(sims, bins=80, color="#3b82f6", alpha=0.8, edgecolor="white")
        ax.axvline(nut.declared_value, color="#22c55e", linewidth=2.5,
                   linestyle="-", label=f"Declared: {nut.declared_value} {nut.unit}")
        ax.axvline(np.mean(sims), color="#ef4444", linewidth=2,
                   linestyle="--", label=f"Actual Mean: {np.mean(sims):.2f} {nut.unit}")
        ax.set_title(f"{nut.name.title()} — Distribution vs Declared", fontsize=13, fontweight="bold")
        ax.set_xlabel(f"{nut.name.title()} ({nut.unit})")
        ax.legend(fontsize=10)
        ax.grid(axis="y", alpha=0.3)
        chart_b64 = _fig_to_base64(fig)

        comp_rate = comp["compliance_rate"] * 100
        risk = comp["risk_level"]

        charts_html += f"""
        <div class="card">
            <h2>{nut.name.title()}</h2>
            <div class="metric-grid">
                <div class="metric">
                    <div class="label">Declared</div>
                    <div class="value">{nut.declared_value} {nut.unit}</div>
                </div>
                <div class="metric">
                    <div class="label">Actual Mean</div>
                    <div class="value">{np.mean(sims):.2f} {nut.unit}</div>
                </div>
                <div class="metric {'green' if comp_rate >= 95 else 'red'}">
                    <div class="label">Compliance</div>
                    <div class="value">{comp_rate:.1f}%</div>
                </div>
                <div class="metric">
                    <div class="label">Risk Level</div>
                    <div class="value">{risk}</div>
                </div>
            </div>
            <img class="chart" src="data:image/png;base64,{chart_b64}" alt="{nut.name} Chart">
        </div>
        """

    summary_table = result.summary().to_html(index=False, classes="")

    content = f"""
    <div class="card">
        <h2>📋 Nutrition Label Compliance — {result.regulation}</h2>
        <div class="metric-grid">
            <div class="metric {overall_color}">
                <div class="label">Overall Compliance</div>
                <div class="value">{overall * 100:.1f}%</div>
                <div class="detail">All nutrients simultaneously</div>
            </div>
            <div class="metric">
                <div class="label">Regulation</div>
                <div class="value">{result.regulation}</div>
            </div>
            <div class="metric">
                <div class="label">Nutrients Tested</div>
                <div class="value">{len(result.nutrients)}</div>
            </div>
            <div class="metric">
                <div class="label">Simulations</div>
                <div class="value">{result.n_simulations:,}</div>
            </div>
        </div>
        {summary_table}
    </div>
    {charts_html}
    """

    html = _html_wrapper("Nutritional Label Compliance", content)
    with open(filepath, "w") as f:
        f.write(html)
    print(f"📄 Report saved: {filepath}")
    return filepath
